apiVersion: v1
kind: Secret
metadata:
  name: streamforge-secret
  namespace: streamforge
type: Opaque
stringData:
  MYSQL_USERNAME: "root"
  MYSQL_PASSWORD: "Zc112325!"
  LIVEKIT_API_KEY: "devkey"
  LIVEKIT_API_SECRET: "secret"
  LIVEKIT_KEYS: "devkey: secret"

