spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:streamforge}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai"
    username: "${MYSQL_USERNAME:streamforge}"
    password: "${MYSQL_PASSWORD:streamforge_password}"
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false