port: 7880
bind_addresses:
  - "0.0.0.0"

rtc:
  node_ip: "192.168.1.13"
  tcp_port: 7881
  port_range_start: 30000
  port_range_end: 30100
  use_external_ip: false

redis:
  address: redis:6379

keys:
  devkey: secret
